name: docker

on:
  push:
  workflow_dispatch:
    inputs:
      build_parents:
        description: 'Build parents images'
        type: boolean
  schedule:
    - cron: '0 12 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - run: wget -O run https://raw.githubusercontent.com/minidocks/images/master/run
      - env:
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          BUILD_PARENTS: ${{ github.event.inputs.build_parents }}
        run: bash ./run github:build_and_push
